<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'category_id' => 4,
                'product_name' => 'Eden Cheese',
                'variation' => '430g',
                'description' => '<p>Cheese</p>',
                'availability' => 15,
                'price' => 130.00,
                'discounted_price' => 125,
                'barcode' => 0,
                'image_folder' => 'eden-cheese',
                'created_at' => null,
                'updated_at' => '2022-12-06 07:54:22',
            ],
            [
                'category_id' => 4,
                'product_name' => 'Eden Cheese',
                'variation' => '165g',
                'description' => '<p>Cheese</p>',
                'availability' => 10,
                'price' => 50.00,
                'discounted_price' => 48,
                'barcode' => 0,
                'image_folder' => 'eden-cheese',
                'created_at' => null,
                'updated_at' => '2022-05-15 19:14:41',
            ],
            [
                'category_id' => 9,
                'product_name' => 'Datu Puti Soy Sauce',
                'variation' => '1L',
                'description' => '<p>Datu Puti Soy Sauce Bottle</p>',
                'availability' => 50,
                'price' => 54.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'datu-puti-soy-sauce',
                'created_at' => null,
                'updated_at' => '2022-05-15 18:26:50',
            ],
            [
                'category_id' => 9,
                'product_name' => 'Datu Puti Vinegar',
                'variation' => '1L',
                'description' => 'Vinegar',
                'availability' => 12,
                'price' => 45.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'datu-puti-vinegar',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 9,
                'product_name' => 'Knorr Liquid Seasoning',
                'variation' => '1L',
                'description' => 'Soy Sauce',
                'availability' => 12,
                'price' => 245.00,
                'discounted_price' => 235,
                'barcode' => 0,
                'image_folder' => 'knorr-liquid-seasoning',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 9,
                'product_name' => 'KikkoMan',
                'variation' => '1L',
                'description' => 'Seasoning',
                'availability' => 10,
                'price' => 180.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'kikkoman',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 9,
                'product_name' => 'Peotraco Corn Syrup',
                'variation' => '1L',
                'description' => 'Corn Syrup',
                'availability' => 10,
                'price' => 100.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'peotraco-corn-syrup',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 9,
                'product_name' => 'Peotraco Glucose Syrup',
                'variation' => '750g',
                'description' => 'Glucose Syrup',
                'availability' => 12,
                'price' => 80.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'peotraco-glucose-syrup',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 4,
                'product_name' => 'Alaska Classic Condensed',
                'variation' => '168ml',
                'description' => 'Condense Milk',
                'availability' => 12,
                'price' => 58.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'alaska-classic-condensed',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 4,
                'product_name' => 'Alaska Evaporada',
                'variation' => '370ml',
                'description' => 'Evaporated Filled Milk',
                'availability' => 12,
                'price' => 27.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'alaska-evaporada',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 4,
                'product_name' => 'OK Cheese',
                'variation' => '500g',
                'description' => 'Cheese',
                'availability' => 10,
                'price' => 98.00,
                'discounted_price' => 95,
                'barcode' => 0,
                'image_folder' => 'ok-cheese',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 4,
                'product_name' => 'Ok Cheese',
                'variation' => '200g',
                'description' => 'Cheese',
                'availability' => 12,
                'price' => 40.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'ok-cheese',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 10,
                'product_name' => 'Faspack',
                'variation' => '750ml',
                'description' => 'Microwavable',
                'availability' => 12,
                'price' => 60.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'faspack',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 10,
                'product_name' => 'Faspack',
                'variation' => '500ml',
                'description' => 'Microwavable',
                'availability' => 12,
                'price' => 50.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'faspack',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 10,
                'product_name' => 'Shure',
                'variation' => '750ml',
                'description' => 'Microwavable',
                'availability' => 0,
                'price' => 60.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'shure',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 10,
                'product_name' => 'Shure',
                'variation' => '500ml',
                'description' => 'Microwavable',
                'availability' => 5,
                'price' => 50.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'shure',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 9,
                'product_name' => 'Taihing Mushroom',
                'variation' => '425g',
                'description' => 'Mushroom',
                'availability' => 12,
                'price' => 45.00,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'taihing-mushroom',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'category_id' => 11,
                'product_name' => 'Dove Conditioner',
                'variation' => '10ml',
                'description' => 'Hair Conditioner',
                'availability' => 99,
                'price' => 6.25,
                'discounted_price' => null,
                'barcode' => 0,
                'image_folder' => 'dove-conditioner',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
